### ISSUE TITLE
When a sale is completed it pushes the item to Reverb as a new Product

### ISSUE THREAD

**Issue by proaudio** [reverbdotcom/magento#5] opened 2015-08-27 19:32 UTC
Whenever a sale is completed on our Magento website it pushes the item to Reverb as a New Draft Product even if the item "Sync to Reverb" is set to NO. Do you have any idea why this may be happening?

**Comment by skwp** [comment] 2015-08-28 19:17
@proaudio we believe this is fixed in the latest release - can you please check the 0.2.4 release?

**Comment by proaudio** [comment] 2015-08-28 21:09
I just installed it 2 days ago so it is the newest release. Thanks!
 
Best Regards,
 
Dale Rowley
 
 <http://www.proaudioland.com/> affiliateLogo234x60
Pro Audio Land
3200 Fujita Street
Torrance, CA 90505
310-787-0777
Toll Free 877-671-2200
 <http://www.proaudioland.com/> http://www.proaudioland.com
 
 <https://www.robly.com/subscribe?a=34ac9250bc85b282ed09effb490347f8> newsletterSignupEmailButton

**Comment by skwp** [comment] 2015-08-28 21:11
Ok thanks for reporting, we'll get back to you next week on this! For now I recommend turning draft creation off globally in settings. Does that help?

**Comment by proaudio** [comment] 2015-08-28 21:11
Yes I already turned it off. Thanks!

**Comment by skwp** [comment] 2015-08-31 14:11
@dunagan5887 this still appears to be an issue. do you have time to walk through it today?

**Comment by skwp** [comment] 2015-09-02 18:27
@dunagan5887 we have several confirmed reports of this. I think if people have "create drafts" turned on then an Order is causing a Product Update (inventory change?) which is causing a Create on Reverb. Even if "create drafts" is on, it should only be creating new drafts from an explicit product save or bulk sync. If this distinction is not possible, we should only do it through bulk sync then.

**Comment by dunagan5887** [comment] 2015-09-02 19:29
I may be mistaken here, but I was under the understanding that an order placement should trigger a listing create/update on order placement (due to inventory change). If this is not the case, I can disable the event observer to prevent listings from being created/updated due to an order placement. The logic chain is given below:

Reverb_ReverbSync_Model_Observer::orderSave() - Event called on order placement
Reverb_ReverbSync_Helper_Sync_Product::executeIndividualProductDataSync() called on all purchased products by the event observer
Reverb_ReverbSync_Helper_Data::createOrUpdateReverbListing() - Called ONLY IF product's rev_sync attribute value is not explicitly set to NO
Reverb_ReverbSync_Helper_Data::createObject() - Called if the product is not currently listed on Reverb
Reverb_ReverbSync_Helper_Sync_Product::isListingCreationEnabled() - First line of method createObject(). Checks the System -> Configuration setting for Listing Creation

I have just tested this logic chain on a base Magento 1.9.2 install with Listing Creation Disabled and a product with rev_sync set to true.

**Comment by skwp** [comment] 2015-09-02 19:30
We do want to _update_ listings on order placement due to inventory change. However if the listing is not already on Reverb, we should not create it. This is counterintuitive and unexpected as they may not be on Reverb with good reason. 

Probably the easiest fix is only create listings during bulk sync.

**Comment by skwp** [comment] 2015-09-02 19:31
is `rev_sync` being read anywhere? I don't see it used actually

**Comment by dunagan5887** [comment] 2015-09-02 19:39
Reverb_ReverbSync_Helper_Sync_Product::_productIsExcludedFromSync
Line 94
$revSync = $product -> getRevSync();

This is where rev_sync is being read.

I'll proceed with a patch to limit the order placement to only UPDATING listings, not CREATING any listings

**Comment by skwp** [comment] 2015-09-02 19:40
Thanks, great

**Comment by dunagan5887** [comment] 2015-09-02 19:42
I likely won't be able to get that complete until tomorrow due to a commitment tonight. I will definitely have it done tomorrow though, and should have the order sync done by EOD Friday as well.

**Comment by skwp** [comment] 2015-09-04 20:02
Fixed in https://github.com/reverbdotcom/magento/commit/177358d4f0d077eb8d0d333bba685ca788157d04

**Closed by skwp** 2015-09-04 20:02 UTC
Labels: bug
